language_resources = {
    'en' :{
        'Press SPACE' : 'Press SPACE to continue',
        'Hi' : 'Hi',
        'Quit' : 'QUIT',
        'Language' : 'LANGUAGE',
        'Music' : 'MUSIC',
        'History' : 'HISTORY',
        'Select map' : 'SELECT THIS MAP',
        'Map size' : 'MAP SIZE',
        'Small' : 'SMALL',
        'Medium' : 'MEDIUM',
        'Large' : 'LARGE',
        'Money' : 'Money',
        'Minigame' : 'MINIGAME',
        'Size' : 'SIZE',
        'Credits' : 'CREDITS',
        'Back' : 'BACK',
        'Previous' : 'PREV',
        'Next' : 'NEXT',
        'Bet money' : 'BET MONEY',
        'Choose your player set' : 'CHOOSE YOUR PLAYER SET',
        'Confirm' : 'CONFIRM',
        'Choose your player' : 'CHOOSE YOUR PLAYER',
        'Rank' : 'Rank',
        'Leaderboard' : 'LEADERBOARD',
        'Result' : 'RESULT',
        'Your rank' : 'Your rank',
        'You earned' : 'You earned',
        'You lost' : 'You lost',
        'Total money' : 'Total money',
    },

    'vn': {
        'Press SPACE' : 'Nhan SPACE de tiep tuc',
        'Hi' : 'Chao',
        'Quit' : 'Thoat',
        'Language' : 'NGON NGU',
        'Music' : 'AM NHAC',
        'History' : 'LICH SU',
        'Select map' : 'CHON BAN DO',
        'Map size' : 'KICH THUOC BAN DO',
        'Small' : 'NHO',
        'Medium' : 'VUA',
        'Large' : 'LON',
        'Money' : 'Tien',
        'Minigame' : 'MINIGAME',
        'Size' : 'Kich thuoc',
        'Credits' : 'THONG TIN',
        'Back' : 'QUAY LAI',
        'Previous' : 'TRUOC',
        'Next' : 'SAU',
        'Bet money' : 'DAT CUOC',
        'Choose your player set' : 'CHON BO CAU THU',
        'Confirm' : 'XAC NHAN',
        'Choose your player' : 'CHON CAU THU',
        'Rank' : 'Xep hang',
        'Leaderboard' : 'BANG XEP HANG',
        'Result' : 'Ket qua',
        'Your rank' : 'Ban xep hang',
        'You earned' : 'Ban da kiem duoc',
        'You lost' : 'Ban da mat',
        'Total money' : 'Tong so tien',
    }
}

